asp mvc sample with course udemi/Models/Bill.cs
namespace asp_mvc_sample_with_course_udemi.Models
{
    public class Bill
    {
        public int Id { get; set; }

        public int CustomerId { get; set; }
        public Customer Customer { get; set; }

        public decimal TotalAmount { get; set; }

        public DateTime BillDate { get; set; }

        public PaymentType PaymentType { get; set; }
    }

    public enum PaymentType
    {
        Cash,
        Card
    }
}

asp mvc sample with course udemi/ViewModels/BillViewModel.cs
using asp_mvc_sample_with_course_udemi.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;

namespace asp_mvc_sample_with_course_udemi.ViewModels
{
    public class BillViewModel
    {
        public int CustomerId { get; set; }

        public string CustomerName { get; set; }

        public PaymentType PaymentType { get; set; }

        [Display(Name = "Items List")]
        public int ItemId { get; set; }

        //public List<SelectListItem> ItemList { get; set; }
        public decimal ItemPrice { get; set; }

        public int Quantity { get; set; }

        public int Discount { get; set; }
        public decimal Total { get; set; }

        public decimal GrandTotal { get; set; }

        public List<ItemList> Items { get; set; } = new List<ItemList>();
    }
}

asp mvc sample with course udemi/Controllers/BillsController.cs
using asp_mvc_sample_with_course_udemi.Models;
using asp_mvc_sample_with_course_udemi.Services;
using asp_mvc_sample_with_course_udemi.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace asp_mvc_sample_with_course_udemi.Controllers
{
    public class BillsController : Controller
    {
        private readonly IItemService itemService;
        private readonly ICustomerService customerService;
        private readonly IBillService billService;

        public BillsController(IItemService itemService, ICustomerService customerService, IBillService billService)
        {
            this.itemService = itemService;
            this.customerService = customerService;
            this.billService = billService;
        }

        public async Task<IActionResult> Create()
        {
            var items = await itemService.GetAll();

            ViewBag.ItemsList = new SelectList(items, "Id", "Name");

            return View();
        }

        public async Task<IActionResult> GetPrice(int id)
        {
            var item = await itemService.GetById(id);

            return Json(item.Price);
        }

        public async Task<IActionResult> SaveItems(BillViewModel vm)
        {
            Customer customer = new Customer();
            customer.Name = vm.CustomerName;
            await customerService.AddCustomer(customer);

            var billDetails = new List<BillDetails>();
            foreach (var item in vm.Items)
            {
                billDetails.Add(new BillDetails
                {
                    CustomerId = customer.Id,
                    ItemId = item.ItemId,
                    ItemName = item.ItemName,
                    Price = item.ItemPrice,
                    Discount = item.ItemDiscount,
                    Quantity = item.ItemQuantity,
                    Total = item.ItemTotal
                });
            }

            await billService.AddBillDetails(billDetails);

            var bill = new Bill();
            bill.CustomerId = customer.Id;
            bill.BillDate = DateTime.UtcNow;
            bill.TotalAmount = vm.GrandTotal;

            await billService.AddBill(bill);

            var billReceiptVm = new BillReceiptViewModel()
            {
                BillNumber = bill.Id,
                BillDetails = billDetails,
                CustomerName = vm.CustomerName,
                TotalAmount = vm.GrandTotal,
                FromAddress = "MyRestaurant",
            };

            return PartialView("_bill", billReceiptVm);
        }
    }
}

asp mvc sample with course udemi/Controllers/ItemsController.cs
using asp_mvc_sample_with_course_udemi.Models;
using asp_mvc_sample_with_course_udemi.Services;
using asp_mvc_sample_with_course_udemi.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace asp_mvc_sample_with_course_udemi.Controllers
{
    [AutoValidateAntiforgeryToken]
    public class ItemsController : Controller
    {
        private readonly IItemService itemService;

        public ItemsController(IItemService itemService)
        {
            this.itemService = itemService;
        }

        public async Task<IActionResult> Index()
        {
            var list = new List<ItemViewModel>();
            var items = await itemService.GetAll();
            list.AddRange(items.Select(item => new ItemViewModel { Id = item.Id, Name = item.Name, Price = item.Price }));

            return View(list);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateItemViewModel vm)
        {
            var model = new Item
            {
                Name = vm.Name,
                Price = vm.Price,
            };
            await itemService.SaveItem(model);

            return RedirectToAction("Index");
        }


        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var item = await itemService.GetById(id);
            var vm = new ItemViewModel
            {
                Id = item.Id,
                Name = item.Name,
                Price = item.Price,
            };
            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(ItemViewModel vm)
        {
            var model = new Item
            {
                Id = vm.Id,
                Name = vm.Name,
                Price = vm.Price,
            };
            await itemService.UpdateItem(model);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            await itemService.DeleteItem(id);

            return RedirectToAction("Index");
        }
    }
}

asp mvc sample with course udemi/Views/Shared/_HeaderNav.cshtml
<nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">            
            <img src="https://png.pngtree.com/png-clipart/20220903/ourmid/pngtree-chef-restaurant-logo-png-image_6136204.png" width="100" height="100"/>
            </a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link active" asp-action="Index" asp-controller="Items">
                        Items                        
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-action="Create" asp-controller="Bills">Generate Bill</a>
                </li>                              
            </ul>
            @* <form class="d-flex">
                <input class="form-control me-sm-2" type="search" placeholder="Search">
                <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
            </form> *@
        </div>
    </div>
</nav>

asp mvc sample with course udemi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />    
    <title>@ViewData["Title"] - asp_mvc_sample_with_course_udemi</title>    
    <link rel="stylesheet" href="~/css/yeti.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/asp_mvc_sample_with_course_udemi.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <partial name="_HeaderNav"/>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - asp_mvc_sample_with_course_udemi - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

asp mvc sample with course udemi/Views/Shared/_bill.cshtml
@using asp_mvc_sample_with_course_udemi.ViewModels
@model BillReceiptViewModel

<div class="container">
    <!-- Row with Bill Information -->
    <div class="row">
        <!-- Left Column with Basic Info -->
        <div class="col-md-6">            
            <p><strong>Bill Number:</strong> #@Model.BillNumber</p>
            <p><strong>From Address:</strong> @Model.FromAddress</p>
        </div>
        <!-- Right Column with Customer Info -->
        <div class="col-md-6">            
            <p><strong>Customer Name:</strong> @Model.CustomerName</p>
            <p><strong>Total Amount:</strong> @Model.TotalAmount USD</p>
        </div>
    </div>

    <!-- Row with Table of Bill Details -->
    <div class="row">
        <div class="col-12">
            <h3>Bill Details</h3>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col">Item Number</th>
                        <th scope="col">Item Name</th>
                        <th scope="col">Price</th>
                        <th scope="col">Quantity</th>
                        <th scope="col">Dis. (%)</th>
                        <th scope="col">Total</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.BillDetails)
                    {
                        <tr>
                            <td>@item.ItemId</td>
                            <td>@item.ItemName</td>
                            <td>@item.Price</td>
                            <td>@item.Quantity</td>
                            <td>@item.Discount</td>
                            <td>@item.Total</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>